"""
Cookie parsing and serialization utilities supporting Netscape and JSON formats.
"""

import json
import re
from typing import Any, Dict, List, Optional, Tuple

REQUIRED_COOKIE_KEYS = ("SID", "__Secure-1PSID", "__Secure-1PSIDTS", "OSID")


def parse_netscape_cookies(raw_text: str) -> List[Dict[str, Any]]:
    """Parse Netscape/Mozilla cookies.txt format, preserving attributes."""
    cookies = []
    for line in (raw_text or "").splitlines():
        line = line.strip()
        if not line:
            continue

        http_only = line.startswith("#HttpOnly_")
        if http_only:
            line = line[len("#HttpOnly_"):]
        elif line.startswith("#"):
            continue

        parts = line.split("\t") if "\t" in line else re.split(r"\s+", line)
        parts = [p.strip() for p in parts]
        if len(parts) >= 7:
            domain, _flag, path, secure_str, expiry_str, name, value = parts[:7]
            cookies.append({
                "name": name,
                "value": value,
                "domain": domain,
                "path": path,
                "secure": secure_str.upper() == "TRUE",
                "http_only": http_only,
                "expires": int(expiry_str) if expiry_str.isdigit() else 0,
            })
    return cookies


def parse_json_cookies(raw_text: str) -> List[Dict[str, Any]]:
    """Parse JSON cookie export format (list or object with cookies array)."""
    try:
        payload = json.loads(raw_text)
    except (TypeError, ValueError, json.JSONDecodeError):
        return []

    items = []
    if isinstance(payload, dict):
        if isinstance(payload.get("cookies"), list):
            items = payload["cookies"]
        else:
            return [
                {
                    "name": k.strip(),
                    "value": str(v).strip(),
                    "domain": ".google.com",
                    "path": "/",
                    "secure": True,
                    "http_only": False,
                    "expires": 0,
                }
                for k, v in payload.items()
                if isinstance(k, str) and k.strip() and v is not None
            ]
    elif isinstance(payload, list):
        items = payload

    cookies = []
    for item in items:
        if not isinstance(item, dict):
            continue
        name = (item.get("name") or "").strip()
        value = str(item.get("value") or "").strip()
        if name and value:
            cookies.append({
                "name": name,
                "value": value,
                "domain": (item.get("domain") or ".google.com").strip(),
                "path": (item.get("path") or "/").strip(),
                "secure": bool(item.get("secure", False)),
                "http_only": bool(item.get("httpOnly") or item.get("http_only", False)),
                "expires": int(item.get("expirationDate") or item.get("expires") or 0),
            })
    return cookies


def parse_cookie_source(source: str) -> Tuple[List[Dict[str, Any]], List[str]]:
    """
    Parse cookies from raw text (auto-detecting JSON or Netscape format).
    Returns (cookies_list, missing_keys).
    """
    clean = (source or "").strip()
    while len(clean) >= 2 and clean[0] in ("'", '"') and clean[-1] == clean[0]:
        clean = clean[1:-1].strip()

    if not clean:
        return [], list(REQUIRED_COOKIE_KEYS)

    parsed = parse_json_cookies(clean)
    if not parsed:
        parsed = parse_netscape_cookies(clean)

    found_names = {item["name"]: item["value"] for item in parsed if isinstance(item, dict) and item.get("name")}
    missing = [key for key in REQUIRED_COOKIE_KEYS if not found_names.get(key)]
    return parsed, missing


def format_netscape_cookies(cookies: List[Dict[str, Any]]) -> str:
    """Format cookie list as standard Netscape HTTP cookie file text."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# http://curl.haxx.se/rfc/cookie_spec.html",
        "# This file was generated by photos-engine",
        "",
    ]
    for c in cookies:
        domain = c.get("domain") or ".google.com"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        http_only = "#HttpOnly_" if c.get("http_only", False) else ""
        expires = c.get("expires", 0) or 0
        name = c.get("name", "")
        value = c.get("value", "")
        if name:
            lines.append(f"{http_only}{domain}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def build_cookie_header(cookies: List[Dict[str, Any]]) -> str:
    """Build a standard Cookie request header string."""
    parts = []
    for c in cookies:
        name = c.get("name")
        val = c.get("value")
        if name and val:
            parts.append(f"{name}={val}")
    return "; ".join(parts)
