package core

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/sardanioss/httpcloak"
)

// CookieItem represents a single HTTP cookie with full attributes (matching system/cookies/services.py).
type CookieItem struct {
	Name     string `json:"name"`
	Value    string `json:"value"`
	Domain   string `json:"domain,omitempty"`
	Path     string `json:"path,omitempty"`
	Secure   bool   `json:"secure,omitempty"`
	HttpOnly bool   `json:"http_only,omitempty"`
	Expires  int64  `json:"expires,omitempty"`
}

// Cookie represents a complete, unfiltered cookie collection for Google Photos Web sessions.
type Cookie struct {
	Items []CookieItem `json:"items"`
}

// Get returns the value of a cookie by name.
func (c Cookie) Get(name string) string {
	for _, item := range c.Items {
		if item.Name == name {
			return item.Value
		}
	}
	return ""
}

// SetItem appends or updates a cookie in the session preserving all its attributes.
func (c *Cookie) SetItem(item CookieItem) {
	if item.Name == "" {
		return
	}
	for i, existing := range c.Items {
		if existing.Name == item.Name {
			c.Items[i] = item
			return
		}
	}
	c.Items = append(c.Items, item)
}

// LoadIntoSession injects all cookies with their full attributes into an httpcloak.Session jar.
func (c Cookie) LoadIntoSession(s *httpcloak.Session) {
	if s == nil {
		return
	}
	for _, item := range c.Items {
		domain := item.Domain
		if domain == "" {
			domain = ".google.com"
		}
		path := item.Path
		if path == "" {
			path = "/"
		}
		var exp *time.Time
		if item.Expires > 0 {
			t := time.Unix(item.Expires, 0)
			exp = &t
		}
		s.SetCookie(httpcloak.CookieInfo{
			Name:     item.Name,
			Value:    item.Value,
			Domain:   domain,
			Path:     path,
			Secure:   item.Secure,
			HttpOnly: item.HttpOnly,
			Expires:  exp,
		})
	}
}

// CookiesFromSession extracts all cookies from an active httpcloak.Session.
func CookiesFromSession(s *httpcloak.Session) Cookie {
	if s == nil {
		return Cookie{}
	}
	var items []CookieItem
	for _, c := range s.GetCookiesDetailed() {
		var exp int64
		if c.Expires != nil {
			exp = c.Expires.Unix()
		}
		items = append(items, CookieItem{
			Name:     c.Name,
			Value:    c.Value,
			Domain:   c.Domain,
			Path:     c.Path,
			Secure:   c.Secure,
			HttpOnly: c.HttpOnly,
			Expires:  exp,
		})
	}
	return Cookie{Items: items}
}

// BuildCookieHeader formats ALL cookies into a standard Cookie request header without any filtering.
func (c Cookie) BuildCookieHeader() string {
	var parts []string
	for _, item := range c.Items {
		if item.Name != "" && item.Value != "" {
			parts = append(parts, fmt.Sprintf("%s=%s", item.Name, item.Value))
		}
	}
	return strings.Join(parts, "; ")
}

// ToNetscape formats cookies as Netscape HTTP cookie file text (matching build_netscape_cookie_content).
func (c Cookie) ToNetscape() string {
	lines := []string{
		"# Netscape HTTP Cookie File",
		"# http://curl.haxx.se/rfc/cookie_spec.html",
		"# This file was generated by photos-engine",
		"",
	}
	for _, item := range c.Items {
		domain := item.Domain
		if domain == "" {
			domain = ".google.com"
		}
		path := item.Path
		if path == "" {
			path = "/"
		}
		secure := "FALSE"
		if item.Secure {
			secure = "TRUE"
		}
		httpOnly := ""
		if item.HttpOnly {
			httpOnly = "#HttpOnly_"
		}
		lines = append(lines, fmt.Sprintf("%s%s\tTRUE\t%s\t%s\t%d\t%s\t%s",
			httpOnly, domain, path, secure, item.Expires, item.Name, item.Value))
	}
	return strings.Join(lines, "\n") + "\n"
}

// extractFromJSON matches _extract_from_json in system/cookies/services.py.
func extractFromJSON(rawText string) []CookieItem {
	var raw interface{}
	if err := json.Unmarshal([]byte(rawText), &raw); err != nil {
		return nil
	}

	var items []interface{}
	switch val := raw.(type) {
	case []interface{}:
		items = val
	case map[string]interface{}:
		if cookiesList, ok := val["cookies"].([]interface{}); ok {
			items = cookiesList
		} else {
			// Flat {name: value} dictionary
			var result []CookieItem
			for k, v := range val {
				k = strings.TrimSpace(k)
				strV := strings.TrimSpace(fmt.Sprint(v))
				if k != "" && strV != "" && strV != "<nil>" {
					result = append(result, CookieItem{
						Name:     k,
						Value:    strV,
						Domain:   ".google.com",
						Path:     "/",
						Secure:   true,
						HttpOnly: false,
						Expires:  0,
					})
				}
			}
			return result
		}
	default:
		return nil
	}

	var result []CookieItem
	for _, item := range items {
		m, ok := item.(map[string]interface{})
		if !ok {
			continue
		}
		name, _ := m["name"].(string)
		name = strings.TrimSpace(name)
		value := strings.TrimSpace(fmt.Sprint(m["value"]))
		if name == "" || value == "" || value == "<nil>" {
			continue
		}

		domain, _ := m["domain"].(string)
		path, _ := m["path"].(string)
		if path == "" {
			path = "/"
		}
		secure, _ := m["secure"].(bool)
		httpOnly, _ := m["httpOnly"].(bool)
		if !httpOnly {
			httpOnly, _ = m["http_only"].(bool)
		}

		var expires int64
		if expF, ok := m["expirationDate"].(float64); ok {
			expires = int64(expF)
		} else if expF, ok := m["expires"].(float64); ok {
			expires = int64(expF)
		}

		result = append(result, CookieItem{
			Name:     name,
			Value:    value,
			Domain:   domain,
			Path:     path,
			Secure:   secure,
			HttpOnly: httpOnly,
			Expires:  expires,
		})
	}
	return result
}

func isNetscapeLine(parts []string) bool {
	if len(parts) < 7 {
		return false
	}
	c1 := strings.ToUpper(strings.TrimSpace(parts[1]))
	c3 := strings.ToUpper(strings.TrimSpace(parts[3]))
	return (c1 == "TRUE" || c1 == "FALSE") && (c3 == "TRUE" || c3 == "FALSE")
}

// extractFromNetscape matches _extract_from_netscape in system/cookies/services.py.
func extractFromNetscape(rawText string) []CookieItem {
	var result []CookieItem
	lines := strings.Split(rawText, "\n")
	wsRegex := regexp.MustCompile(`\s+`)

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		httpOnly := strings.HasPrefix(line, "#HttpOnly_")
		if httpOnly {
			line = strings.TrimPrefix(line, "#HttpOnly_")
		} else if strings.HasPrefix(line, "#") {
			continue
		}

		var parts []string
		if strings.Contains(line, "\t") {
			parts = strings.Split(line, "\t")
		} else {
			parts = wsRegex.Split(line, -1)
		}

		for i := range parts {
			parts[i] = strings.TrimSpace(parts[i])
		}

		if isNetscapeLine(parts) {
			domain := parts[0]
			path := parts[2]
			secure := strings.EqualFold(parts[3], "TRUE")
			expires, _ := strconv.ParseInt(parts[4], 10, 64)
			name := parts[5]
			value := parts[6]
			if name != "" && value != "" {
				result = append(result, CookieItem{
					Name:     name,
					Value:    value,
					Domain:   domain,
					Path:     path,
					Secure:   secure,
					HttpOnly: httpOnly,
					Expires:  expires,
				})
			}
		}
	}
	return result
}

// extractFromHeader handles raw semicolon-delimited key=value strings.
func extractFromHeader(rawText string) []CookieItem {
	var result []CookieItem
	subParts := strings.Split(rawText, ";")
	for _, sp := range subParts {
		sp = strings.TrimSpace(sp)
		if eqIdx := strings.Index(sp, "="); eqIdx != -1 {
			name := strings.TrimSpace(sp[:eqIdx])
			val := strings.TrimSpace(sp[eqIdx+1:])
			if name != "" && val != "" {
				result = append(result, CookieItem{
					Name:     name,
					Value:    val,
					Domain:   ".google.com",
					Path:     "/",
					Secure:   true,
					HttpOnly: false,
					Expires:  0,
				})
			}
		}
	}
	return result
}

// ParseCookies parses raw cookies string (auto-detecting JSON, Netscape, or key=value header format).
// Matches extract_required_cookie_values in system/cookies/services.py without dropping any cookies.
func ParseCookies(raw string) (Cookie, error) {
	clean := strings.TrimSpace(raw)
	for len(clean) >= 2 && (clean[0] == '\'' || clean[0] == '"') && clean[len(clean)-1] == clean[0] {
		clean = strings.TrimSpace(clean[1 : len(clean)-1])
	}
	if clean == "" {
		return Cookie{}, errors.New("empty cookie string")
	}

	// 1. Try JSON format
	items := extractFromJSON(clean)

	// 2. Try Netscape format
	if len(items) == 0 {
		items = extractFromNetscape(clean)
	}

	// 3. Try Semicolon-delimited header format
	if len(items) == 0 {
		items = extractFromHeader(clean)
	}

	if len(items) == 0 {
		return Cookie{}, errors.New("no valid Google auth cookies found in input")
	}

	return Cookie{Items: items}, nil
}

// CheckCookieStatus verifies cookie validity and retrieves the logged-in email using httpcloak.
// Follow-redirects is explicitly disabled (WithoutRedirects) to prevent redirect poisoning.
func CheckCookieStatus(cookie Cookie) (*CookieStatus, error) {
	s := httpcloak.NewSession(
		"firefox-latest",
		httpcloak.WithoutRedirects(),
		httpcloak.WithSessionTimeout(15*time.Second),
	)
	defer s.Close()

	cookie.LoadIntoSession(s)

	checkURL := fmt.Sprintf("https://photos.google.com/?_t=%d", time.Now().Unix())
	resp, err := s.Get(context.Background(), checkURL)
	if err != nil {
		return nil, fmt.Errorf("network error: %w", err)
	}
	defer resp.Close()

	location := resp.GetHeader("Location")
	if resp.StatusCode != 200 || strings.Contains(location, "accounts.google.com") || strings.Contains(location, "photos/about") {
		return &CookieStatus{
			Valid:   false,
			Message: "Cookies are expired or redirected to login.",
		}, nil
	}

	bodyStr, err := resp.Text()
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Pattern 1: oPEP7c
	accountRe := regexp.MustCompile(`"oPEP7c"\s*:\s*"([^"]+@[^"]+)"`)
	if match := accountRe.FindStringSubmatch(bodyStr); len(match) > 1 {
		account := strings.TrimSpace(match[1])
		return &CookieStatus{
			Valid:   true,
			Account: account,
			Message: fmt.Sprintf("Cookies are valid (Account: %s)", account),
		}, nil
	}

	// Pattern 2: Generic email structure
	emailRe := regexp.MustCompile(`([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})`)
	if match := emailRe.FindStringSubmatch(bodyStr); len(match) > 1 {
		account := strings.TrimSpace(match[1])
		return &CookieStatus{
			Valid:   true,
			Account: account,
			Message: fmt.Sprintf("Cookies are valid (Account: %s)", account),
		}, nil
	}

	return &CookieStatus{
		Valid:   true,
		Message: "Cookies are valid (Account email could not be parsed).",
	}, nil
}
